[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers importantes para MIME types
[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Content-Type" = "text/css"